include:
  - board: xiao_ble
    shield: kimiboard rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=n -DCONFIG_ZMK_STUDIO_LOCKING=n
      -DZMK_EXTRA_MODULES="$GITHUB_WORKSPACE;$GITHUB_WORKSPACE/modules/zmk-pmw3610-driver"
      -DCONFIG_PMW3610=y
  - board: xiao_ble
    shield: settings_reset
